[build]
nixPkgs = [
  "php",
  "php82Extensions.curl",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "nodejs",
  "chromium",
  "nss"
]

[deploy]
start = "php artisan serve --host=0.0.0.0 --port=8080"
